FROM jenkins/jenkins:lts

USER root

# Install dependencies
RUN apt-get update -qq && \
    apt-get install -qqy \
        apt-transport-https \
        ca-certificates \
        curl \
        gnupg \
        lsb-release

# Add GPG key
RUN curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

# Add the Docker repository
RUN echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
    https://download.docker.com/linux/debian $(lsb_release -cs) stable" \
    > /etc/apt/sources.list.d/docker.list

# Install Docker CE
RUN apt-get update -qq && \
    apt-get install -qqy docker-ce docker-ce-cli containerd.io

# Add to Docker group
RUN usermod -aG docker jenkins

